name: Duster Lint

on:
  pull_request:

jobs:
  duster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Duster Lints"
        uses: tighten/duster-action@v2
        with:
          args: lint
