name: SDK Tests
on: workflow_dispatch
jobs:
  tests:
    name: SDK Tests
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql, gd
      - name: Install composer dependencies
        run: composer install
      - name: Run tests
        run: php artisan test
        env:
          COYFI_KEY: ${{ secrets.COYFI_KEY }}
          COYFI_SECRET: ${{ secrets.COYFI_SECRET }}
